name: GitHub Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: >-
      github.event.pull_request.merged && github.event.pull_request.title == 'chore: release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          gh release create "v${VERSION}" --generate-notes --title "v${VERSION}"
