name: update agent skills

on:
  schedule:
    - cron: "0 12 * * 3"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update skills and open pull request
        id: skills
        uses: iyaki/skills-update@v1.0.1
        with:
            create-pr: true

